"""
Markdown Report Generator for WAIO Audit Tool.
Converts the audit report JSON into a structured Markdown file.
"""
from datetime import datetime

PILLAR_META = {
    "semantic_html": "Semantic HTML",
    "structured_data": "Structured Data",
    "aeo_content": "AEO Content",
    "css_quality": "CSS Quality",
    "js_bloat": "JS Bloat",
    "accessibility": "Accessibility",
}


def generate_markdown(report: dict) -> str:
    """Generate a Markdown string from the audit report dict."""
    url = report.get("url", "Unknown")
    timestamp = report.get("audit_timestamp", "")
    try:
        ts_display = datetime.fromisoformat(timestamp.replace("Z", "+00:00")).strftime("%b %d, %Y %I:%M %p UTC")
    except Exception:
        ts_display = timestamp

    overall_score = report.get("overall_score", 0)
    overall_label = report.get("overall_label", "N/A")
    summary = report.get("summary", {})

    if report.get("is_competitive"):
        return _generate_competitive_markdown(report, ts_display)

    lines = [
        f"# WAIO Audit Report",
        f"",
        f"**URL:** {url}  ",
        f"**Date:** {ts_display}  ",
        f"**Overall Score:** {overall_score}/100 — {overall_label}",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total Issues | {summary.get('total_findings', 0)} |",
        f"| Critical | {summary.get('critical', 0)} |",
        f"| High | {summary.get('high', 0)} |",
        f"| Medium | {summary.get('medium', 0)} |",
        f"",
    ]

    # Pillar Scores
    lines.append("## Pillar Scores")
    lines.append("")
    lines.append("| Pillar | Score | Rating |")
    lines.append("|--------|-------|--------|")
    for key, cat in report.get("categories", {}).items():
        label = PILLAR_META.get(key, key)
        score = cat.get("score", 0)
        rating = cat.get("label", "N/A")
        lines.append(f"| {label} | {score}/100 | {rating} |")
    lines.append("")

    # Top Priorities
    priorities = summary.get("top_priorities", [])
    if priorities:
        lines.append("## Top Priorities")
        lines.append("")
        for i, p in enumerate(priorities, 1):
            lines.append(f"{i}. {p}")
        lines.append("")

    # Positive Findings
    positives = report.get("positive_findings", [])
    if positives:
        lines.append("## What's Working Well")
        lines.append("")
        for p in positives[:8]:
            text = p.get("text", p) if isinstance(p, dict) else p
            anchor = p.get("credibility_anchor") if isinstance(p, dict) else None
            lines.append(f"- ✅ {text}")
            if anchor:
                lines.append(f"  > *{anchor}*")
        lines.append("")

    # Detailed Findings
    lines.append("## Detailed Findings")
    lines.append("")
    for cat_key, cat_val in report.get("categories", {}).items():
        label = PILLAR_META.get(cat_key, cat_key)
        findings = []
        for chk in (cat_val.get("checks") or {}).values():
            if isinstance(chk, dict) and "findings" in chk:
                findings.extend(chk["findings"])
        if not findings:
            continue

        findings.sort(key=lambda f: {"critical": 0, "high": 1, "medium": 2}.get(f.get("severity", ""), 3))

        lines.append(f"### {label} ({len(findings)} issues)")
        lines.append("")
        for f in findings:
            sev = f.get("severity", "medium").upper()
            desc = f.get("description", "")
            rec = f.get("recommendation", "")
            anchor = f.get("credibility_anchor")
            lines.append(f"- **[{sev}]** {desc}")
            lines.append(f"  - *Recommendation:* {rec}")
            if anchor:
                lines.append(f"  - > 📌 *{anchor}*")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [WAIO Audit Engine](https://www.vezadigital.com) — Deterministic, evidence-based Webflow analysis.*")
    lines.append("")

    return "\n".join(lines)


def _generate_competitive_markdown(report: dict, timestamp: str) -> str:
    """Generate a Markdown string for a competitive benchmarking report."""
    primary_url = report.get("primary_url", "Unknown")
    rankings = report.get("rankings", [])
    pillar_averages = report.get("pillar_averages", {})
    pillar_labels = report.get("pillar_labels", {})
    advantages = report.get("advantages", [])
    weaknesses = report.get("weaknesses", [])

    lines = [
        f"# WAIO Competitive AI-Readiness Benchmark",
        f"",
        f"**Primary URL:** {primary_url}  ",
        f"**Date:** {timestamp}  ",
        f"**Rank:** #{report.get('primary', {}).get('rank', 1)} of {len(rankings)}",
        f"",
        f"---",
        f"",
        f"## Leaderboard",
        f"",
        f"| Rank | URL | Score | Rating |",
        f"|------|-----|-------|--------|",
    ]

    for r in rankings:
        url_disp = r['url'].replace('https://', '').replace('http://', '')
        primary_tag = " **(YOUR SITE)**" if r['url'] == primary_url else ""
        lines.append(f"| {r['rank']} | {url_disp}{primary_tag} | {r['overall_score']} | {r['overall_label']} |")

    lines.append("")
    lines.append("## Pillar Comparison")
    lines.append("")
    
    # Header: | Pillar | Primary | Comp 1 | Comp 2 | Average |
    header = ["| Pillar"]
    separator = ["|--------"]
    for r in rankings:
        url_disp = r['url'].replace('https://', '').replace('http://', '')[:15]
        header.append(f" {url_disp} ")
        separator.append("-------")
    header.append(" Average |")
    separator.append("---------|")
    
    lines.append("".join(header))
    lines.append("".join(separator))

    for key, label in pillar_labels.items():
        row = [f"| {label} "]
        for r in rankings:
            score = r['pillar_scores'].get(key, 0)
            row.append(f" {score} ")
        row.append(f" {pillar_averages.get(key, 0)} |")
        lines.append("".join(row))

    lines.append("")
    
    if advantages:
        lines.append("## Competitive Advantages")
        lines.append("")
        for adv in advantages:
            lines.append(f"- **{adv['pillar']}**: {adv['score']} (Avg: {adv['average']}) — *+{adv['diff']} pts above average*")
        lines.append("")

    if weaknesses:
        lines.append("## Critical Gaps")
        lines.append("")
        for weak in weaknesses:
            lines.append(f"- **{weak['pillar']}**: {weak['score']} (Avg: {weak['average']}) — *{weak['diff']} pts below average*")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [WAIO Audit Engine](https://www.vezadigital.com) — Deterministic, evidence-based Webflow analysis.*")
    lines.append("")

    return "\n".join(lines)
