import { useMemo } from 'react';
import { useParams, Link } from 'react-router';
import { motion } from 'framer-motion';
import { ArrowLeft, FolderTree, Info, Loader2, AlertCircle } from 'lucide-react';
import { useAuditStore } from '../stores/auditStore';
import { useEnrichmentPolling } from '../hooks/useEnrichmentPolling';

interface Cluster {
  prefix: string;
  page_count: number;
  urls?: string[];
  dominant_category?: string;
  coherence_score?: number;
  category_breakdown?: Record<string, number>;
}

const cohesionColor = (score: number): string => {
  if (score >= 0.8) return '#22C55E';
  if (score >= 0.6) return '#EAB308';
  return '#EF4444';
};

const CLUSTER_COLORS = [
  '#6366F1', '#22D3EE', '#F472B6', '#34D399', '#FBBF24',
  '#A78BFA', '#FB923C', '#60A5FA', '#4ADE80', '#F87171',
  '#818CF8', '#2DD4BF',
];

export default function DashboardClustersPage() {
  const { auditId } = useParams();
  const report = useAuditStore((s) => s.report);
  const enrichment = useEnrichmentPolling(auditId);

  const clusters = useMemo(() => {
    // Primary source: link_analysis.clusters (written by build_link_graph)
    const raw =
      report?.link_analysis?.clusters ??
      report?.clusters ??
      report?.topic_clusters ??
      null;
    if (!raw || (Array.isArray(raw) && raw.length === 0)) return null;
    if (Array.isArray(raw)) return raw as Cluster[];
    // If it's an object keyed by path
    return Object.entries(raw).map(([prefix, data]) => ({
      prefix,
      ...(data as Record<string, unknown>),
    })) as Cluster[];
  }, [report]);

  const totalClusteredPages = useMemo(() => {
    if (!clusters) return 0;
    return clusters.reduce((sum, c) => sum + (c.page_count || 0), 0);
  }, [clusters]);

  const totalPages = report?.link_analysis?.stats?.total_pages ?? 0;
  const uncategorizedCount = totalPages > 0 ? Math.max(0, totalPages - totalClusteredPages) : 0;
  const maxPageCount = clusters ? Math.max(...clusters.map(c => c.page_count || 0)) : 1;

  return (
    <div className="p-6 lg:p-8 max-w-5xl mx-auto space-y-6">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Link
          to={`/dashboard/${auditId}`}
          className="inline-flex items-center gap-1.5 text-xs text-text-muted hover:text-text transition-colors mb-4"
        >
          <ArrowLeft size={12} />
          Back to Overview
        </Link>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-accent/10 rounded-xl flex items-center justify-center">
            <FolderTree size={20} className="text-accent" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-text font-heading">
              Topic Clusters
            </h1>
            <p className="text-sm text-text-secondary mt-0.5">
              How your content is organized into topical groups.
            </p>
          </div>
        </div>
      </motion.div>

      {/* Enrichment loading state */}
      {!clusters && enrichment.status === 'polling' ? (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface-raised border border-border rounded-xl p-10 text-center"
        >
          <Loader2 size={32} className="text-indigo-500 animate-spin mx-auto mb-4" />
          <p className="text-sm font-semibold text-text mb-1">
            Topic clusters are being generated
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            This section is being generated by our crawler. It typically takes 2-5 minutes.
          </p>
          {enrichment.progress && (
            <p className="text-xs text-indigo-600 mt-3">{enrichment.progress}</p>
          )}
        </motion.div>
      ) : !clusters && enrichment.status === 'failed' ? (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface-raised border border-border rounded-xl p-10 text-center"
        >
          <AlertCircle size={32} className="text-amber-500 mx-auto mb-4" />
          <p className="text-sm font-semibold text-text mb-1">
            Crawl data could not be generated
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            Please try running the audit again.
          </p>
        </motion.div>
      ) : clusters && clusters.length > 0 ? (
        <>
          {/* Summary stats */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.05 }}
            className="grid grid-cols-2 md:grid-cols-4 gap-3"
          >
            <div className="bg-surface-raised border border-border rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-text font-heading">{clusters.length}</div>
              <div className="text-[10px] text-text-muted uppercase tracking-wider mt-1">Clusters</div>
            </div>
            <div className="bg-surface-raised border border-border rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-text font-heading">{totalClusteredPages}</div>
              <div className="text-[10px] text-text-muted uppercase tracking-wider mt-1">Clustered Pages</div>
            </div>
            <div className="bg-surface-raised border border-border rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-text font-heading">{totalPages}</div>
              <div className="text-[10px] text-text-muted uppercase tracking-wider mt-1">Total Pages</div>
            </div>
            <div className="bg-surface-raised border border-border rounded-xl p-4 text-center">
              <div className={`text-2xl font-bold font-heading ${uncategorizedCount > 0 ? 'text-amber-600' : 'text-text'}`}>
                {uncategorizedCount}
              </div>
              <div className="text-[10px] text-text-muted uppercase tracking-wider mt-1">Uncategorized</div>
            </div>
          </motion.div>

          {/* Cluster list */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="space-y-3"
          >
            {clusters.map((cluster, idx) => (
              <motion.div
                key={cluster.prefix}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.05 * idx }}
                className="bg-surface-raised border border-border rounded-xl p-5"
              >
                <div className="flex items-center justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2.5">
                      <span
                        className="w-3 h-3 rounded-full flex-shrink-0"
                        style={{ backgroundColor: CLUSTER_COLORS[idx % CLUSTER_COLORS.length] }}
                      />
                      <span className="text-sm font-semibold text-text truncate">
                        {cluster.prefix}
                      </span>
                    </div>
                    <div className="flex items-center gap-3 mt-2 ml-5.5">
                      <span className="text-xs text-text-muted">
                        {cluster.page_count ?? '?'} pages
                      </span>
                      {cluster.dominant_category && (
                        <span className="text-[10px] font-semibold text-accent bg-accent/10 px-2 py-0.5 rounded-full">
                          {cluster.dominant_category}
                        </span>
                      )}
                    </div>
                    {/* Proportional bar */}
                    <div className="mt-3 ml-5.5 h-2 bg-gray-100 rounded-full overflow-hidden max-w-sm">
                      <div
                        className="h-full rounded-full transition-all duration-500"
                        style={{
                          width: `${Math.max(4, (cluster.page_count / maxPageCount) * 100)}%`,
                          backgroundColor: CLUSTER_COLORS[idx % CLUSTER_COLORS.length],
                        }}
                      />
                    </div>
                  </div>

                  {cluster.coherence_score != null && (
                    <div className="text-right flex-shrink-0">
                      <div
                        className="text-lg font-extrabold font-heading"
                        style={{ color: cohesionColor(cluster.coherence_score) }}
                      >
                        {Math.round(cluster.coherence_score * 100)}%
                      </div>
                      <div className="text-[10px] text-text-muted font-semibold uppercase tracking-wider">
                        Coherence
                      </div>
                    </div>
                  )}
                </div>

                {/* Category breakdown */}
                {cluster.category_breakdown && Object.keys(cluster.category_breakdown).length > 1 && (
                  <div className="mt-3 ml-5.5 flex flex-wrap gap-1.5">
                    {Object.entries(cluster.category_breakdown)
                      .sort((a, b) => b[1] - a[1])
                      .slice(0, 5)
                      .map(([cat, count]) => (
                        <span
                          key={cat}
                          className="text-[10px] text-text-muted bg-gray-100 px-2 py-0.5 rounded-full"
                        >
                          {cat}: {count}
                        </span>
                      ))}
                  </div>
                )}
              </motion.div>
            ))}
          </motion.div>
        </>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-surface-raised border border-border rounded-xl p-8 text-center"
        >
          <div className="w-12 h-12 mx-auto mb-4 bg-surface-overlay rounded-xl flex items-center justify-center">
            <Info size={20} className="text-text-muted" />
          </div>
          <p className="text-sm font-semibold text-text mb-1">
            Topic Clusters Not Available
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            Topic clusters will be detected after a full site crawl. Run a
            Comprehensive Audit with DataForSEO configured to analyze your
            content architecture.
          </p>
        </motion.div>
      )}
    </div>
  );
}
