import { useParams, Link } from 'react-router';
import { motion } from 'framer-motion';
import { ArrowLeft, Loader2, AlertCircle } from 'lucide-react';
import { useAuditStore } from '../stores/auditStore';
import { useEnrichmentPolling } from '../hooks/useEnrichmentPolling';
import { LinkGraph } from '../components/LinkGraph';

export default function DashboardGraphPage() {
  const { auditId } = useParams();
  const report = useAuditStore((s) => s.report);
  const enrichment = useEnrichmentPolling(auditId);

  const graphData = report?.link_analysis ?? null;
  const hasNodes = !!graphData?.graph?.nodes?.length;

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Link
          to={`/dashboard/${auditId}`}
          className="inline-flex items-center gap-1.5 text-xs text-text-muted hover:text-text transition-colors mb-4"
        >
          <ArrowLeft size={12} />
          Back to Overview
        </Link>
        <h1 className="text-2xl font-bold text-text font-heading">
          Link Graph
        </h1>
        <p className="text-sm text-text-secondary mt-1">
          Interactive visualization of your site's internal link architecture.
        </p>
      </motion.div>

      {/* Contextual loading state when enrichment is still running */}
      {!hasNodes && enrichment.status === 'polling' ? (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface-raised border border-border rounded-2xl p-10 text-center"
        >
          <Loader2 size={32} className="text-indigo-500 animate-spin mx-auto mb-4" />
          <p className="text-sm font-semibold text-text mb-1">
            Link graph is being generated
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            This section is being generated by our crawler. It typically takes 2-5 minutes.
          </p>
          {enrichment.progress && (
            <p className="text-xs text-indigo-600 mt-3">{enrichment.progress}</p>
          )}
          {/* Skeleton shimmer */}
          <div className="mt-6 h-48 bg-gray-100 rounded-xl overflow-hidden relative">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-gray-200/60 to-transparent"
              style={{ animation: 'shimmer 2s ease-in-out infinite' }} />
          </div>
        </motion.div>
      ) : !hasNodes && enrichment.status === 'failed' ? (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface-raised border border-border rounded-2xl p-10 text-center"
        >
          <AlertCircle size={32} className="text-amber-500 mx-auto mb-4" />
          <p className="text-sm font-semibold text-text mb-1">
            Crawl data could not be generated
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            Please try running the audit again. If the problem persists, check your DataForSEO configuration.
          </p>
        </motion.div>
      ) : (
        <LinkGraph auditId={auditId ?? ''} data={graphData} />
      )}
    </div>
  );
}
