import { useParams, Link } from 'react-router';
import { motion } from 'framer-motion';
import { ArrowLeft, Loader2, AlertCircle, RefreshCw } from 'lucide-react';
import { useAuditStore } from '../stores/auditStore';
import { useEnrichmentPolling } from '../hooks/useEnrichmentPolling';
import { LinkGraph } from '../components/LinkGraph';

export default function DashboardGraphPage() {
  const { auditId } = useParams();
  const report = useAuditStore((s) => s.report);
  const enrichment = useEnrichmentPolling(auditId);

  const graphData = report?.link_analysis ?? null;
  const hasNodes = !!graphData?.graph?.nodes?.length;

  const showWaiting = !hasNodes && (enrichment.status === 'polling' || enrichment.status === 'timed_out');

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Link
          to={`/dashboard/${auditId}`}
          className="inline-flex items-center gap-1.5 text-xs text-text-muted hover:text-text transition-colors mb-4"
        >
          <ArrowLeft size={12} />
          Back to Overview
        </Link>
        <h1 className="text-2xl font-bold text-text font-heading">
          Link Graph
        </h1>
        <p className="text-sm text-text-secondary mt-1">
          Interactive visualization of your site's internal link architecture.
        </p>
      </motion.div>

      {showWaiting ? (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface-raised border border-border rounded-2xl p-10 text-center"
        >
          <Loader2 size={32} className="text-indigo-500 animate-spin mx-auto mb-4" />
          <p className="text-sm font-semibold text-text mb-1">
            {enrichment.status === 'timed_out'
              ? 'The site crawl is still processing'
              : 'Link graph is being generated'}
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            {enrichment.status === 'timed_out'
              ? 'This can take up to 20 minutes for larger sites. The graph will appear automatically when ready.'
              : 'This section is being generated by our crawler. It typically takes 2-5 minutes.'}
          </p>
          {enrichment.progress && (
            <p className="text-xs text-indigo-600 mt-3">{enrichment.progress}</p>
          )}
          {enrichment.status === 'timed_out' && (
            <button
              onClick={() => enrichment.refreshNow()}
              disabled={enrichment.isRefreshing}
              className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-700 hover:text-indigo-900 bg-indigo-100 hover:bg-indigo-200 px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50"
            >
              <RefreshCw size={12} className={enrichment.isRefreshing ? 'animate-spin' : ''} />
              {enrichment.isRefreshing ? 'Checking...' : 'Refresh now'}
            </button>
          )}
          {enrichment.status === 'polling' && (
            <div className="mt-6 h-48 bg-gray-100 rounded-xl overflow-hidden relative">
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-gray-200/60 to-transparent"
                style={{ animation: 'shimmer 2s ease-in-out infinite' }} />
            </div>
          )}
        </motion.div>
      ) : !hasNodes && enrichment.status === 'failed' ? (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface-raised border border-border rounded-2xl p-10 text-center"
        >
          <AlertCircle size={32} className="text-amber-500 mx-auto mb-4" />
          <p className="text-sm font-semibold text-text mb-1">
            Crawl data could not be generated
          </p>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            Please try running the audit again. If the problem persists, check your DataForSEO configuration.
          </p>
        </motion.div>
      ) : (
        <LinkGraph auditId={auditId ?? ''} data={graphData} />
      )}
    </div>
  );
}
