import { PILLAR_LABELS } from '../constants/pillarLabels';

export function generateMarkdown(report: Record<string, any>): string {
  const lines: string[] = [];

  lines.push(`# WAIO Intelligence Report`);
  lines.push('');
  lines.push(`**URL:** ${report.url}`);
  lines.push(
    `**Date:** ${new Date(report.audit_timestamp).toLocaleString()}`
  );
  lines.push(`**Overall Score:** ${report.overall_score}/100 (${report.overall_label})`);
  lines.push(`**Tier:** ${report.tier || 'free'}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Findings | ${report.summary?.total_findings ?? 0} |`);
  lines.push(`| Critical | ${report.summary?.critical ?? 0} |`);
  lines.push(`| High | ${report.summary?.high ?? 0} |`);
  lines.push(`| Medium | ${report.summary?.medium ?? 0} |`);
  lines.push('');

  // Pillar Scores
  if (report.categories) {
    lines.push('## Pillar Scores');
    lines.push('');
    lines.push('| Pillar | Score | Rating |');
    lines.push('|--------|-------|--------|');
    for (const [key, cat] of Object.entries(report.categories)) {
      const catObj = cat as Record<string, any>;
      lines.push(
        `| ${PILLAR_LABELS[key] || key} | ${catObj.score ?? '-'} | ${catObj.label ?? '-'} |`
      );
    }
    lines.push('');
  }

  // Findings by pillar
  if (report.categories) {
    lines.push('## Findings');
    lines.push('');
    for (const [key, cat] of Object.entries(report.categories)) {
      const catObj = cat as Record<string, any>;
      const checks = catObj.checks || {};
      const findings: any[] = [];
      for (const check of Object.values(checks)) {
        const checkObj = check as Record<string, any>;
        if (checkObj.findings) findings.push(...checkObj.findings);
      }
      if (findings.length === 0) continue;

      lines.push(`### ${PILLAR_LABELS[key] || key}`);
      lines.push('');
      for (const f of findings) {
        const icon =
          f.severity === 'critical'
            ? '🔴'
            : f.severity === 'high'
              ? '🟠'
              : '🟡';
        lines.push(`${icon} **[${f.severity.toUpperCase()}]** ${f.description}`);
        lines.push('');
        lines.push(`> **Recommendation:** ${f.recommendation}`);
        if (f.reference) lines.push(`> **Reference:** ${f.reference}`);
        lines.push('');
      }
    }
  }

  // Positive findings
  const positives = report.positive_findings || [];
  if (positives.length > 0) {
    lines.push('## Positive Findings');
    lines.push('');
    for (const p of positives) {
      lines.push(`- ✅ ${p}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by WAIO Intelligence — Veza Digital*');
  lines.push('');

  return lines.join('\n');
}

export function downloadMarkdown(report: Record<string, any>): void {
  const md = generateMarkdown(report);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const domain = report.url
    ?.replace(/https?:\/\//, '')
    .replace(/\//g, '_')
    .replace(/_$/, '');
  const date = new Date().toISOString().slice(0, 10);
  a.href = url;
  a.download = `WAIO-Intelligence-Report-${domain}-${date}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
